DELETE FROM `spell_script_names` WHERE `spell_id` = 202709;
DELETE FROM `spell_script_names` WHERE `spell_id` = 193826;
DELETE FROM `spell_script_names` WHERE `spell_id` = 193827;
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (202709, 'spell_aegis_of_agamar');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (193826, 'spell_ragnarok');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (193827, 'spell_ragnarok_damage');
update `creature_template` set `gossip_menu_id` = 18848 where `entry` = 97084;
update `creature_template` set `gossip_menu_id` = 18849 where `entry` = 97083;
update `creature_template` set `gossip_menu_id` = 18850 where `entry` = 95843;
update `creature_template` set `gossip_menu_id` = 18851 where `entry` = 97081;
update `creature_template` set `ScriptName` = "hymdall_storm_drake" where `entry` = 97788;
update `areatrigger_template` set `ScriptName` = "areatrigger_storm_breath" where `Id` = 9705;
update `areatrigger_template` set `ScriptName` = "areatrigger_storm_breath" where `Id` = 9677;
