UPDATE `creature_template` SET `minlevel` = '16', `maxlevel` = '16', `faction` = '16', `VehicleId` = '522', `ScriptName` = 'boss_slagmaw' WHERE `entry` =61463;

DELETE FROM `vehicle_template_accessory` WHERE `entry` = 61463;
INSERT INTO `vehicle_template_accessory` (`entry`, `accessory_entry`, `seat_id`, `minion`, `description`, `summontype`, `summontimer`) VALUES
(61463, 61800, 0, 1, 'Slagmaw', 6, 1000);

DELETE FROM `npc_spellclick_spells` WHERE `npc_entry` = 61463;
INSERT INTO `npc_spellclick_spells` (`npc_entry`, `spell_id`, `cast_flags`, `user_type`) VALUES
(61463, 88066, 1, 0);

UPDATE `creature_template` SET `minlevel` = '16', `maxlevel` = '16', `faction` = '16', `InhabitType` = '4' WHERE `entry` =61800;

UPDATE `creature_template` SET `ScriptName` = 'boss_slagmaw_head' WHERE `entry` =61800;

UPDATE `creature_template` SET `ScriptName` = 'boss_koranthal' WHERE `entry` =61412;

UPDATE `creature_template` SET `ScriptName` = 'boss_adarogg' WHERE `entry` =61408;

UPDATE `creature_template` SET `ScriptName` = 'boss_slagmaw' WHERE `entry` =61463;

UPDATE `creature_template` SET `ScriptName` = 'boss_gordoth' WHERE `entry` =61528;

UPDATE `creature_template` SET `InhabitType` = '4' WHERE `entry` =61463;

Delete from `creature_model_info` where `Displayid` in (16925, 42101, 11686, 31687, 32731, 42208, 42217, 42219, 23865, 23864, 42188, 42187, 42210, 42196, 42198, 42237, 42194, 42211, 42215, 42191, 42213, 42214, 38759, 42212, 42247, 42245, 42232, 42209, 42100);

INSERT INTO `creature_model_info` (`DisplayID`, `BoundingRadius`, `CombatReach`, `DisplayID_Other_Gender`) VALUES(16925, 0.5, 1, 2) ON DUPLICATE KEY UPDATE `DisplayID` = VALUES(`DisplayID`), `BoundingRadius` = VALUES(`BoundingRadius`), `CombatReach` = VALUES(`CombatReach`), `DisplayID_Other_Gender` = VALUES(`DisplayID_Other_Gender`);
INSERT INTO `creature_model_info` (`DisplayID`, `BoundingRadius`, `CombatReach`, `DisplayID_Other_Gender`) VALUES(42101, 0.651, 2.625, 0) ON DUPLICATE KEY UPDATE `DisplayID` = VALUES(`DisplayID`), `BoundingRadius` = VALUES(`BoundingRadius`), `CombatReach` = VALUES(`CombatReach`), `DisplayID_Other_Gender` = VALUES(`DisplayID_Other_Gender`);
INSERT INTO `creature_model_info` (`DisplayID`, `BoundingRadius`, `CombatReach`, `DisplayID_Other_Gender`) VALUES(11686, 0.5, 1, 2) ON DUPLICATE KEY UPDATE `DisplayID` = VALUES(`DisplayID`), `BoundingRadius` = VALUES(`BoundingRadius`), `CombatReach` = VALUES(`CombatReach`), `DisplayID_Other_Gender` = VALUES(`DisplayID_Other_Gender`);
INSERT INTO `creature_model_info` (`DisplayID`, `BoundingRadius`, `CombatReach`, `DisplayID_Other_Gender`) VALUES(31687, 0.9, 1.8, 2) ON DUPLICATE KEY UPDATE `DisplayID` = VALUES(`DisplayID`), `BoundingRadius` = VALUES(`BoundingRadius`), `CombatReach` = VALUES(`CombatReach`), `DisplayID_Other_Gender` = VALUES(`DisplayID_Other_Gender`);
INSERT INTO `creature_model_info` (`DisplayID`, `BoundingRadius`, `CombatReach`, `DisplayID_Other_Gender`) VALUES(32731, 1.2075, 2.25, 0) ON DUPLICATE KEY UPDATE `DisplayID` = VALUES(`DisplayID`), `BoundingRadius` = VALUES(`BoundingRadius`), `CombatReach` = VALUES(`CombatReach`), `DisplayID_Other_Gender` = VALUES(`DisplayID_Other_Gender`);
INSERT INTO `creature_model_info` (`DisplayID`, `BoundingRadius`, `CombatReach`, `DisplayID_Other_Gender`) VALUES(42208, 0.465, 1.875, 0) ON DUPLICATE KEY UPDATE `DisplayID` = VALUES(`DisplayID`), `BoundingRadius` = VALUES(`BoundingRadius`), `CombatReach` = VALUES(`CombatReach`), `DisplayID_Other_Gender` = VALUES(`DisplayID_Other_Gender`);
INSERT INTO `creature_model_info` (`DisplayID`, `BoundingRadius`, `CombatReach`, `DisplayID_Other_Gender`) VALUES(42217, 0.465, 1.875, 0) ON DUPLICATE KEY UPDATE `DisplayID` = VALUES(`DisplayID`), `BoundingRadius` = VALUES(`BoundingRadius`), `CombatReach` = VALUES(`CombatReach`), `DisplayID_Other_Gender` = VALUES(`DisplayID_Other_Gender`);
INSERT INTO `creature_model_info` (`DisplayID`, `BoundingRadius`, `CombatReach`, `DisplayID_Other_Gender`) VALUES(42219, 0.465, 1.875, 0) ON DUPLICATE KEY UPDATE `DisplayID` = VALUES(`DisplayID`), `BoundingRadius` = VALUES(`BoundingRadius`), `CombatReach` = VALUES(`CombatReach`), `DisplayID_Other_Gender` = VALUES(`DisplayID_Other_Gender`);
INSERT INTO `creature_model_info` (`DisplayID`, `BoundingRadius`, `CombatReach`, `DisplayID_Other_Gender`) VALUES(23865, 0.3906, 1.575, 0) ON DUPLICATE KEY UPDATE `DisplayID` = VALUES(`DisplayID`), `BoundingRadius` = VALUES(`BoundingRadius`), `CombatReach` = VALUES(`CombatReach`), `DisplayID_Other_Gender` = VALUES(`DisplayID_Other_Gender`);
INSERT INTO `creature_model_info` (`DisplayID`, `BoundingRadius`, `CombatReach`, `DisplayID_Other_Gender`) VALUES(23864, 0.3906, 1.575, 0) ON DUPLICATE KEY UPDATE `DisplayID` = VALUES(`DisplayID`), `BoundingRadius` = VALUES(`BoundingRadius`), `CombatReach` = VALUES(`CombatReach`), `DisplayID_Other_Gender` = VALUES(`DisplayID_Other_Gender`);
INSERT INTO `creature_model_info` (`DisplayID`, `BoundingRadius`, `CombatReach`, `DisplayID_Other_Gender`) VALUES(42188, 0.459, 3, 2) ON DUPLICATE KEY UPDATE `DisplayID` = VALUES(`DisplayID`), `BoundingRadius` = VALUES(`BoundingRadius`), `CombatReach` = VALUES(`CombatReach`), `DisplayID_Other_Gender` = VALUES(`DisplayID_Other_Gender`);
INSERT INTO `creature_model_info` (`DisplayID`, `BoundingRadius`, `CombatReach`, `DisplayID_Other_Gender`) VALUES(42187, 0.2295, 1.5, 2) ON DUPLICATE KEY UPDATE `DisplayID` = VALUES(`DisplayID`), `BoundingRadius` = VALUES(`BoundingRadius`), `CombatReach` = VALUES(`CombatReach`), `DisplayID_Other_Gender` = VALUES(`DisplayID_Other_Gender`);
INSERT INTO `creature_model_info` (`DisplayID`, `BoundingRadius`, `CombatReach`, `DisplayID_Other_Gender`) VALUES(42210, 0.295, 1.875, 1) ON DUPLICATE KEY UPDATE `DisplayID` = VALUES(`DisplayID`), `BoundingRadius` = VALUES(`BoundingRadius`), `CombatReach` = VALUES(`CombatReach`), `DisplayID_Other_Gender` = VALUES(`DisplayID_Other_Gender`);
INSERT INTO `creature_model_info` (`DisplayID`, `BoundingRadius`, `CombatReach`, `DisplayID_Other_Gender`) VALUES(42196, 0.465, 1.875, 0) ON DUPLICATE KEY UPDATE `DisplayID` = VALUES(`DisplayID`), `BoundingRadius` = VALUES(`BoundingRadius`), `CombatReach` = VALUES(`CombatReach`), `DisplayID_Other_Gender` = VALUES(`DisplayID_Other_Gender`);
INSERT INTO `creature_model_info` (`DisplayID`, `BoundingRadius`, `CombatReach`, `DisplayID_Other_Gender`) VALUES(42198, 0.465, 1.875, 0) ON DUPLICATE KEY UPDATE `DisplayID` = VALUES(`DisplayID`), `BoundingRadius` = VALUES(`BoundingRadius`), `CombatReach` = VALUES(`CombatReach`), `DisplayID_Other_Gender` = VALUES(`DisplayID_Other_Gender`);
INSERT INTO `creature_model_info` (`DisplayID`, `BoundingRadius`, `CombatReach`, `DisplayID_Other_Gender`) VALUES(42237, 0.8100001, 1.5, 2) ON DUPLICATE KEY UPDATE `DisplayID` = VALUES(`DisplayID`), `BoundingRadius` = VALUES(`BoundingRadius`), `CombatReach` = VALUES(`CombatReach`), `DisplayID_Other_Gender` = VALUES(`DisplayID_Other_Gender`);
INSERT INTO `creature_model_info` (`DisplayID`, `BoundingRadius`, `CombatReach`, `DisplayID_Other_Gender`) VALUES(42194, 0.465, 1.875, 0) ON DUPLICATE KEY UPDATE `DisplayID` = VALUES(`DisplayID`), `BoundingRadius` = VALUES(`BoundingRadius`), `CombatReach` = VALUES(`CombatReach`), `DisplayID_Other_Gender` = VALUES(`DisplayID_Other_Gender`);
INSERT INTO `creature_model_info` (`DisplayID`, `BoundingRadius`, `CombatReach`, `DisplayID_Other_Gender`) VALUES(42211, 0.465, 1.875, 0) ON DUPLICATE KEY UPDATE `DisplayID` = VALUES(`DisplayID`), `BoundingRadius` = VALUES(`BoundingRadius`), `CombatReach` = VALUES(`CombatReach`), `DisplayID_Other_Gender` = VALUES(`DisplayID_Other_Gender`);
INSERT INTO `creature_model_info` (`DisplayID`, `BoundingRadius`, `CombatReach`, `DisplayID_Other_Gender`) VALUES(42215, 0.295, 1.875, 1) ON DUPLICATE KEY UPDATE `DisplayID` = VALUES(`DisplayID`), `BoundingRadius` = VALUES(`BoundingRadius`), `CombatReach` = VALUES(`CombatReach`), `DisplayID_Other_Gender` = VALUES(`DisplayID_Other_Gender`);
INSERT INTO `creature_model_info` (`DisplayID`, `BoundingRadius`, `CombatReach`, `DisplayID_Other_Gender`) VALUES(42191, 0.465, 1.875, 0) ON DUPLICATE KEY UPDATE `DisplayID` = VALUES(`DisplayID`), `BoundingRadius` = VALUES(`BoundingRadius`), `CombatReach` = VALUES(`CombatReach`), `DisplayID_Other_Gender` = VALUES(`DisplayID_Other_Gender`);
INSERT INTO `creature_model_info` (`DisplayID`, `BoundingRadius`, `CombatReach`, `DisplayID_Other_Gender`) VALUES(42213, 0.465, 1.875, 0) ON DUPLICATE KEY UPDATE `DisplayID` = VALUES(`DisplayID`), `BoundingRadius` = VALUES(`BoundingRadius`), `CombatReach` = VALUES(`CombatReach`), `DisplayID_Other_Gender` = VALUES(`DisplayID_Other_Gender`);
INSERT INTO `creature_model_info` (`DisplayID`, `BoundingRadius`, `CombatReach`, `DisplayID_Other_Gender`) VALUES(42214, 0.465, 1.875, 0) ON DUPLICATE KEY UPDATE `DisplayID` = VALUES(`DisplayID`), `BoundingRadius` = VALUES(`BoundingRadius`), `CombatReach` = VALUES(`CombatReach`), `DisplayID_Other_Gender` = VALUES(`DisplayID_Other_Gender`);
INSERT INTO `creature_model_info` (`DisplayID`, `BoundingRadius`, `CombatReach`, `DisplayID_Other_Gender`) VALUES(38759, 0.918, 6, 2) ON DUPLICATE KEY UPDATE `DisplayID` = VALUES(`DisplayID`), `BoundingRadius` = VALUES(`BoundingRadius`), `CombatReach` = VALUES(`CombatReach`), `DisplayID_Other_Gender` = VALUES(`DisplayID_Other_Gender`);
INSERT INTO `creature_model_info` (`DisplayID`, `BoundingRadius`, `CombatReach`, `DisplayID_Other_Gender`) VALUES(42212, 0.465, 1.875, 0) ON DUPLICATE KEY UPDATE `DisplayID` = VALUES(`DisplayID`), `BoundingRadius` = VALUES(`BoundingRadius`), `CombatReach` = VALUES(`CombatReach`), `DisplayID_Other_Gender` = VALUES(`DisplayID_Other_Gender`);
INSERT INTO `creature_model_info` (`DisplayID`, `BoundingRadius`, `CombatReach`, `DisplayID_Other_Gender`) VALUES(42247, 6, 24, 2) ON DUPLICATE KEY UPDATE `DisplayID` = VALUES(`DisplayID`), `BoundingRadius` = VALUES(`BoundingRadius`), `CombatReach` = VALUES(`CombatReach`), `DisplayID_Other_Gender` = VALUES(`DisplayID_Other_Gender`);
INSERT INTO `creature_model_info` (`DisplayID`, `BoundingRadius`, `CombatReach`, `DisplayID_Other_Gender`) VALUES(42245, 6, 15, 2) ON DUPLICATE KEY UPDATE `DisplayID` = VALUES(`DisplayID`), `BoundingRadius` = VALUES(`BoundingRadius`), `CombatReach` = VALUES(`CombatReach`), `DisplayID_Other_Gender` = VALUES(`DisplayID_Other_Gender`);
INSERT INTO `creature_model_info` (`DisplayID`, `BoundingRadius`, `CombatReach`, `DisplayID_Other_Gender`) VALUES(42232, 1, 0, 2) ON DUPLICATE KEY UPDATE `DisplayID` = VALUES(`DisplayID`), `BoundingRadius` = VALUES(`BoundingRadius`), `CombatReach` = VALUES(`CombatReach`), `DisplayID_Other_Gender` = VALUES(`DisplayID_Other_Gender`);
INSERT INTO `creature_model_info` (`DisplayID`, `BoundingRadius`, `CombatReach`, `DisplayID_Other_Gender`) VALUES(42209, 0.465, 1.875, 0) ON DUPLICATE KEY UPDATE `DisplayID` = VALUES(`DisplayID`), `BoundingRadius` = VALUES(`BoundingRadius`), `CombatReach` = VALUES(`CombatReach`), `DisplayID_Other_Gender` = VALUES(`DisplayID_Other_Gender`);
INSERT INTO `creature_model_info` (`DisplayID`, `BoundingRadius`, `CombatReach`, `DisplayID_Other_Gender`) VALUES(42100, 2.75, 5.775, 0) ON DUPLICATE KEY UPDATE `DisplayID` = VALUES(`DisplayID`), `BoundingRadius` = VALUES(`BoundingRadius`), `CombatReach` = VALUES(`CombatReach`), `DisplayID_Other_Gender` = VALUES(`DisplayID_Other_Gender`);
